#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v10
# autospec commit: 5905be9
#
Name     : R-survMisc
Version  : 0.5.6
Release  : 3
URL      : https://cran.r-project.org/src/contrib/survMisc_0.5.6.tar.gz
Source0  : https://cran.r-project.org/src/contrib/survMisc_0.5.6.tar.gz
Summary  : Miscellaneous Functions for Survival Data
Group    : Development/Tools
License  : GPL-2.0
Requires: R-KMsurv
Requires: R-data.table
Requires: R-ggplot2
Requires: R-gridExtra
Requires: R-km.ci
Requires: R-knitr
Requires: R-xtable
Requires: R-zoo
BuildRequires : R-KMsurv
BuildRequires : R-data.table
BuildRequires : R-ggplot2
BuildRequires : R-gridExtra
BuildRequires : R-km.ci
BuildRequires : R-knitr
BuildRequires : R-xtable
BuildRequires : R-zoo
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
right-censored survival data. These extend the methods available in

%prep
%setup -q -n survMisc

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1713980734

%install
export SOURCE_DATE_EPOCH=1713980734
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/survMisc/DESCRIPTION
/usr/lib64/R/library/survMisc/INDEX
/usr/lib64/R/library/survMisc/Meta/Rd.rds
/usr/lib64/R/library/survMisc/Meta/data.rds
/usr/lib64/R/library/survMisc/Meta/features.rds
/usr/lib64/R/library/survMisc/Meta/hsearch.rds
/usr/lib64/R/library/survMisc/Meta/links.rds
/usr/lib64/R/library/survMisc/Meta/nsInfo.rds
/usr/lib64/R/library/survMisc/Meta/package.rds
/usr/lib64/R/library/survMisc/Meta/vignette.rds
/usr/lib64/R/library/survMisc/NAMESPACE
/usr/lib64/R/library/survMisc/NEWS.Rd
/usr/lib64/R/library/survMisc/R/survMisc
/usr/lib64/R/library/survMisc/R/survMisc.rdb
/usr/lib64/R/library/survMisc/R/survMisc.rdx
/usr/lib64/R/library/survMisc/data/Rdata.rdb
/usr/lib64/R/library/survMisc/data/Rdata.rds
/usr/lib64/R/library/survMisc/data/Rdata.rdx
/usr/lib64/R/library/survMisc/doc/index.html
/usr/lib64/R/library/survMisc/doc/plots.R
/usr/lib64/R/library/survMisc/doc/plots.Rnw
/usr/lib64/R/library/survMisc/doc/plots.pdf
/usr/lib64/R/library/survMisc/help/AnIndex
/usr/lib64/R/library/survMisc/help/aliases.rds
/usr/lib64/R/library/survMisc/help/paths.rds
/usr/lib64/R/library/survMisc/help/survMisc.rdb
/usr/lib64/R/library/survMisc/help/survMisc.rdx
/usr/lib64/R/library/survMisc/html/00Index.html
/usr/lib64/R/library/survMisc/html/R.css
